In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
print('Outputs given')

Outputs given

In [2]:
data_file = r'C:\Users\rsaxe\Downloads\Care_To_Compare\Care_To_Compare\Wind Farm A\Wind Farm A\datasets\0.csv'
df = pd.read_csv(data_file, sep =";")

In [3]:
df.head()

,time_stamp,asset_id,id,train_test,status_type_id,sensor_0_avg,sensor_1_avg,sensor_2_avg,wind_speed_3_avg,wind_speed_4_avg,...,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg
0,2022-08-03 06:10:00,0,0,train,0,22.0,302.9,129.4,1.7,1.7,...,-496.0,0.0,0.0,-1280.0,-496.0,0.0,0.0,0.0,0.0,26.0
1,2022-08-03 06:20:00,0,1,train,0,22.0,307.1,133.6,1.7,1.7,...,-490.0,0.0,0.0,-1278.0,-490.0,0.0,0.0,0.0,0.0,25.0
2,2022-08-03 06:30:00,0,2,train,0,22.0,340.6,167.1,0.9,0.9,...,-490.0,0.0,0.0,-1356.0,-490.0,0.0,0.0,0.0,0.0,25.0
3,2022-08-03 06:40:00,0,3,train,0,22.0,124.4,-49.1,1.5,1.5,...,-509.0,0.0,0.0,-1274.0,-509.0,0.0,0.0,0.0,0.0,26.0
4,2022-08-03 06:50:00,0,4,train,0,22.0,66.2,-107.3,1.0,1.0,...,-499.0,0.0,0.0,-1284.0,-499.0,0.0,0.0,0.0,0.0,26.0

* ``time_stamp``: Time stamps in 10 minute frequency. Time stamps have been anonymized in order to not reveal the identity of the wind farms.
* ``asset_id``: Wind turbine ID. This can be used to find out which events took place on the same wind turbine. The IDs have also been anonymized.
* ``id``: An additional ID for each time stamp. This is supposed to prevent confusion with different time formats.
* ``train_test``: Strings describing whether the timestamp is part of the prediction data or the training data of the dataset.
* ``status_type``: Status of the wind turbine at the given time stamp. There are 6 different status IDs where status 0 and 2 are considered normal operation:
  * 0: Normal Operation - The turbine is in normal power production mode 
  * 1: Derated Operation - Derated power generation with a power restriction
  * 2: Idling - Asset is idling and waits to operate again
  * 3: Service - Asset is in service mode / service team is at the site
  * 4: Downtime - Asset is down due a fault or other reasons
  * 5: Other - Other operational states

In [4]:
df.tail()

,time_stamp,asset_id,id,train_test,status_type_id,sensor_0_avg,sensor_1_avg,sensor_2_avg,wind_speed_3_avg,wind_speed_4_avg,...,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg
54981,2023-08-23 05:30:00,0,54981,prediction,3,25.0,121.0,24.6,3.3,0.0,...,-17.0,0.0,0.0,-166.0,-17.0,0.0,0.0,0.0,0.0,24.0
54982,2023-08-23 05:40:00,0,54982,prediction,3,25.0,117.2,20.9,2.8,0.0,...,-17.0,0.0,0.0,-167.0,-17.0,0.0,0.0,0.0,0.0,24.0
54983,2023-08-23 05:50:00,0,54983,prediction,3,25.0,114.5,18.2,2.7,0.0,...,-17.0,0.0,0.0,-166.0,-17.0,0.0,0.0,0.0,0.0,24.0
54984,2023-08-23 06:00:00,0,54984,prediction,3,25.0,104.4,8.0,3.1,0.0,...,-17.0,0.0,0.0,-167.0,-17.0,0.0,0.0,0.0,0.0,24.0
54985,2023-08-23 06:10:00,0,54985,prediction,3,25.0,101.8,5.4,3.4,0.0,...,-17.0,0.0,0.0,-167.0,-17.0,0.0,0.0,0.0,0.0,24.0

In [16]:
df[df['train_test'] == 'prediction']

,time_stamp,asset_id,id,train_test,status_type_id,sensor_0_avg,sensor_1_avg,sensor_2_avg,wind_speed_3_avg,wind_speed_4_avg,...,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg
52148,2023-08-03 06:10:00,0,52148,prediction,0,26.0,186.7,-165.1,1.5,1.5,...,-2451.0,0.0,0.0,-1356.0,-2451.0,0.0,0.0,0.0,0.0,29.0
52149,2023-08-03 06:20:00,0,52149,prediction,0,26.0,203.4,-148.5,1.1,1.1,...,-2435.0,0.0,0.0,-1368.0,-2435.0,0.0,0.0,0.0,0.0,29.0
52150,2023-08-03 06:30:00,0,52150,prediction,0,26.0,181.7,-170.2,1.3,1.3,...,-2411.0,0.0,0.0,-1345.0,-2411.0,0.0,0.0,0.0,0.0,29.0
52151,2023-08-03 06:40:00,0,52151,prediction,0,26.0,156.5,164.6,1.6,1.6,...,-2414.0,0.0,0.0,-1350.0,-2414.0,0.0,0.0,0.0,0.0,29.0
52152,2023-08-03 06:50:00,0,52152,prediction,0,26.0,155.9,164.0,1.6,1.6,...,-2412.0,0.0,0.0,-1359.0,-2412.0,0.0,0.0,0.0,0.0,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54981,2023-08-23 05:30:00,0,54981,prediction,3,25.0,121.0,24.6,3.3,0.0,...,-17.0,0.0,0.0,-166.0,-17.0,0.0,0.0,0.0,0.0,24.0
54982,2023-08-23 05:40:00,0,54982,prediction,3,25.0,117.2,20.9,2.8,0.0,...,-17.0,0.0,0.0,-167.0,-17.0,0.0,0.0,0.0,0.0,24.0
54983,2023-08-23 05:50:00,0,54983,prediction,3,25.0,114.5,18.2,2.7,0.0,...,-17.0,0.0,0.0,-166.0,-17.0,0.0,0.0,0.0,0.0,24.0
54984,2023-08-23 06:00:00,0,54984,prediction,3,25.0,104.4,8.0,3.1,0.0,...,-17.0,0.0,0.0,-167.0,-17.0,0.0,0.0,0.0,0.0,24.0
54985,2023-08-23 06:10:00,0,54985,prediction,3,25.0,101.8,5.4,3.4,0.0,...,-17.0,0.0,0.0,-167.0,-17.0,0.0,0.0,0.0,0.0,24.0

In [8]:
feature_disc = pd.read_csv(r'C:\Users\rsaxe\Downloads\Care_To_Compare\Care_To_Compare\Wind Farm A\Wind Farm A\feature_description.csv', sep = ";")
feature_disc

,sensor_name,statistics_type,description,unit,is_angle,is_counter
0,sensor_0,average,Ambient temperature,ï¿½C,False,False
1,sensor_1,average,Wind absolute direction,ï¿½,True,False
2,sensor_2,average,Wind relative direction,ï¿½,True,False
3,wind_speed_3,"maximum,minimum,average,std_dev",Windspeed,m/s,False,False
4,wind_speed_4,average,Estimated windspeed,m/s,False,False
5,sensor_5,"maximum,minimum,std_dev,average",Pitch angle,ï¿½,True,False
6,sensor_6,average,Temperature in the hub controller,ï¿½C,False,False
7,sensor_7,average,Temperature in the top nacelle controller,ï¿½C,False,False
8,sensor_8,average,Temperature in the choke coils on the VCS-section,ï¿½C,False,False
9,sensor_9,average,Temperature on the VCP-board,ï¿½C,False,False
10,sensor_10,average,Temperature in the VCS cooling water,ï¿½C,False,False
11,sensor_11,average,Temperature in gearbox bearing on high speed s...,ï¿½C,False,False
12,sensor_12,average,Temperature oil in gearbox,ï¿½C,False,False
13,sensor_13,average,Temperature in generator bearing 2 (Drive End),ï¿½C,False,False
14,sensor_14,average,Temperature in generator bearing 1 (Non-Drive ...,ï¿½C,False,False
15,sensor_15,average,Temperature inside generator in stator winding...,ï¿½C,False,False
16,sensor_16,average,Temperature inside generator in stator winding...,ï¿½C,False,False
17,sensor_17,average,Temperature inside generator in stator winding...,ï¿½C,False,False
18,sensor_18,"maximum,minimum,average,std_dev",Generator rpm in latest period,rpm,False,False
19,sensor_19,average,Temperature in the split ring chamber,ï¿½C,False,False
20,sensor_20,average,Temperature in the busbar section,ï¿½C,False,False
21,sensor_21,average,Temperature measured by the IGBT-driver on the...,ï¿½C,False,False
22,sensor_22,average,Actual phase displacement,NaN,False,False
23,sensor_23,average,Averaged current in phase 1,A,False,False
24,sensor_24,average,Averaged current in phase 2,A,False,False
25,sensor_25,average,Averaged current in phase 3,A,False,False
26,sensor_26,average,Grid frequency,Hz,False,False
27,reactive_power_27,"average,maximum,minimum,std_dev",Possible grid capacitive reactive power,kVAr,False,False
28,reactive_power_28,"average,maximum,minimum,std_dev",Possible grid inductive reactive power,kVAr,False,False
29,power_29,"maximum,std_dev,average,minimum",Possible grid active power,kW,False,False
30,power_30,"maximum,std_dev,minimum,average",Grid power,kW,False,False
31,sensor_31,"average,maximum,minimum,std_dev",Grid reactive power,kVAr,False,False
32,sensor_32,average,Averaged voltage in phase 1,V,False,False
33,sensor_33,average,Averaged voltage in phase 2,V,False,False
34,sensor_34,average,Averaged voltage in phase 3,V,False,False
35,sensor_35,average,Temperature measured by the IGBT-driver on the...,ï¿½C,False,False
36,sensor_36,average,Temperature measured by the IGBT-driver on the...,ï¿½C,False,False
37,sensor_37,average,Temperature measured by the IGBT-driver on the...,ï¿½C,False,False
38,sensor_38,average,Temperature in HV transformer phase L1,ï¿½C,False,False
39,sensor_39,average,Temperature in HV transformer phase L2,ï¿½C,False,False
40,sensor_40,average,Temperature in HV transformer phase L3,ï¿½C,False,False
41,sensor_41,average,Temperature oil in hydraulic group,ï¿½C,False,False
42,sensor_42,average,Nacelle direction,ï¿½,True,False
43,sensor_43,average,Nacelle temperature,ï¿½C,False,False
44,sensor_44,average,Active power - generator disconnected,Wh,False,False
45,sensor_45,average,Active power - generator connected in delta,Wh,False,False
46,sensor_46,average,Active power - generator connected in star,Wh,False,False
47,sensor_47,average,Reactive power - generator disconnected,VArh,False,False
48,sensor_48,average,Reactive power - generator connected in delta,VArh,False,False
49,sensor_49,average,Reactive power - generator connected in star,VArh,False,False
50,sensor_50,average,Total active power,Wh,False,False
51,sensor_51,average,Total reactive power,VArh,False,False
52,sensor_52,"minimum,average,std_dev,maximum",Rotor rpm,rpm,False,False
53,sensor_53,average,Temperature in the nose cone,ï¿½C,False,False

In [9]:
pd.DataFrame(df.nunique())

                    0
time_stamp      54986
asset_id            1
id              54986
train_test          2
status_type_id      3
...               ...
sensor_52_avg     150
sensor_52_max     144
sensor_52_min     127
sensor_52_std      74
sensor_53_avg      38

[86 rows x 1 columns]

* ``time_stamp``: Time stamps in 10 minute frequency. Time stamps have been anonymized in order to not reveal the identity of the wind farms.
* ``asset_id``: Wind turbine ID. This can be used to find out which events took place on the same wind turbine. The IDs have also been anonymized.
* ``id``: An additional ID for each time stamp. This is supposed to prevent confusion with different time formats.
* ``train_test``: Strings describing whether the timestamp is part of the prediction data or the training data of the dataset.
* ``status_type``: Status of the wind turbine at the given time stamp. There are 6 different status IDs where status 0 and 2 are considered normal operation:
  * 0: Normal Operation - The turbine is in normal power production mode 
  * 1: Derated Operation - Derated power generation with a power restriction
  * 2: Idling - Asset is idling and waits to operate again
  * 3: Service - Asset is in service mode / service team is at the site
  * 4: Downtime - Asset is down due a fault or other reasons
  * 5: Other - Other operational states

In [10]:
print(df['status_type_id'].value_counts())

status_type_id
0    41514
5    12265
3     1207
Name: count, dtype: int64

In [13]:
event_dataset = r'C:\Users\rsaxe\Downloads\Care_To_Compare\Care_To_Compare\Wind Farm A\Wind Farm A\event_info.csv'

In [14]:
event = pd.read_csv(event_dataset, sep =';')

In [17]:
event.sort_values(by='event_id')

,event_id,event_label,event_start,event_start_id,event_end,event_end_id,event_description
4,0,anomaly,2023-08-05 06:10:00,52436,2023-08-19 06:10:00,54447,Generator bearing failure
15,3,normal,2023-04-27 03:00:00,52185,2023-05-18 01:10:00,55198,NaN
8,10,anomaly,2023-10-12 08:40:00,52611,2023-10-19 08:40:00,53591,Gearbox failure
13,13,normal,2023-05-02 13:20:00,50859,2023-05-23 10:20:00,53865,NaN
19,14,normal,2023-03-04 14:00:00,52584,2023-03-11 18:40:00,53620,NaN
16,17,normal,2023-11-03 15:20:00,52597,2023-11-17 00:40:00,54513,NaN
1,22,anomaly,2023-08-11 09:50:00,51888,2023-08-18 10:00:00,52892,Hydraulic group
14,24,normal,2023-04-26 15:00:00,52720,2023-05-10 11:20:00,54714,NaN
11,25,normal,2023-05-22 06:50:00,52289,2023-06-04 02:30:00,54135,NaN
5,26,anomaly,2023-10-12 10:20:00,52261,2023-10-19 10:20:00,53269,Hydraulic group
17,38,normal,2023-06-30 15:40:00,52723,2023-07-14 07:40:00,54546,NaN
6,40,anomaly,2023-12-24 00:00:00,51363,2024-01-24 13:00:00,55870,Generator bearing failure
7,42,anomaly,2023-09-08 15:50:00,52303,2023-09-15 15:50:00,53309,Hydraulic group
9,45,anomaly,2023-04-19 18:10:00,52731,2023-04-26 18:10:00,53738,Hydraulic group
21,51,normal,2023-10-07 01:30:00,52331,2023-10-18 16:10:00,54003,NaN
0,68,anomaly,2023-07-29 13:20:00,52063,2023-08-12 13:10:00,54076,Transformer failure
12,69,normal,2023-09-03 00:50:00,52364,2023-09-17 00:50:00,54380,NaN
18,71,normal,2024-01-01 00:00:00,52439,2024-01-15 00:00:00,54455,NaN
2,72,anomaly,2023-10-09 08:40:00,52497,2023-10-16 08:40:00,53505,Gearbox failure
3,73,anomaly,2023-06-09 11:40:00,52745,2023-06-16 11:40:00,53753,Hydraulic group
10,84,anomaly,2023-09-04 15:30:00,52623,2023-09-11 15:30:00,53627,Hydraulic group
20,92,normal,2023-04-05 02:30:00,52437,2023-04-14 10:00:00,53778,NaN